name: "Packages build"
description: "Packages build"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.203'

    - uses: dotnet/nbgv@f088059084cb5d872e9d1a994433ca6440c2bf72 # v0.4.2
      name: NBGV
      id: nbgv
      with:
        toolVersion: 3.6.139
        setAllVars: true

    - name: Generate Informational Version
      id: NBGV_InformationalVersion
      shell: pwsh
      run: |
        $InformationalVersion="${{ steps.nbgv.outputs.SemVer2 }}+${{ steps.nbgv.outputs.BuildingRef }}".Replace("refs/heads/","").Replace("/","-")
        echo "Informational Version: $InformationalVersion"
        echo "NBGV_InformationalVersion=$InformationalVersion" >> $GITHUB_ENV

    - name: Pack Uno.Sdk
      shell: pwsh
      run: |
        $adjustedPackageVersion="${{ steps.nbgv.outputs.SemVer2 }}".ToLower();

        & dotnet build src/Uno.Sdk/Uno.Sdk.csproj -c Release -p:PackageVersion=$adjustedPackageVersion -p:Version=${{ steps.nbgv.outputs.SimpleVersion }} /bl:./artifacts/uno.sdk-pack.binlog -o ./artifacts

    - name: Pack Templates
      shell: pwsh
      run: |
        $adjustedPackageVersion="${{ steps.nbgv.outputs.SemVer2 }}".ToLower();

        & dotnet build src/Uno.Templates/Uno.Templates.csproj -c Release -p:PackageVersion=$adjustedPackageVersion -p:Version=${{ steps.nbgv.outputs.SimpleVersion }} /bl:./artifacts/uno.templates-pack.binlog -o ./artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts
