jobs:
- job: unit_test
  cancelTimeoutInMinutes: 0
  displayName: Unit Tests
  pool:
    vmImage: $(windowsAgent)
  steps:
    - checkout: self
      fetchDepth: 0

    - template: ../steps/install-dependencies.yml

    - task: PowerShell@2
      displayName: 'Build MyExtensionsApp.1.Tests (Release)'
      inputs:
        targetType: 'inline'
        script: 'dotnet build ./MyExtensionsApp.1.Tests/MyExtensionsApp.1.Tests.csproj -c Release /p:OverrideTargetFramework=$baseTargetFramework$'
        failOnStderr: true
        pwsh: true

    - task: VSTest@3
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\MyExtensionsApp.1.Tests.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        runTestsInIsolation: true
        codeCoverageEnabled: true
        rerunFailedTests: true
