name: "SDK Update"
description: "Update Uno Sdk"

inputs:
  branch:  # id of input
    description: 'base branch'
    required: true
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.401'

    - uses: dotnet/nbgv@f088059084cb5d872e9d1a994433ca6440c2bf72 # v0.4.2
      id: nbgv
      with:
        toolVersion: 3.6.139
        setAllVars: true

    - name: Run Uno Sdk Updater
      run: dotnet run -c Release --project tools/Uno.Sdk.Updater
      shell: pwsh