name: "Sign Packages"
description: "Sign Packages"

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
      name: nuget-packages
      path: artifacts\NuGet

  - name: Setup .NET SDK
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '9.0.300'

  - name: Setup SignClient
    shell: pwsh
    run: dotnet tool install --tool-path . sign --version 0.9.1-beta.25278.1

  # Login to Azure using a ServicePrincipal configured to authenticate against a GitHub Action
  - name: 'Az CLI login'
    uses: azure/login@v1
    with:
      allow-no-subscriptions: true
      client-id: ${{ secrets.SIGN_AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.SIGN_AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.SIGN_AZURE_SUBSCRIPTION_ID }}

  # Run the signing command
  - name: Sign artifacts
    shell: pwsh
    run: >
      ./sign code azure-key-vault
      artifacts\NuGet\*.nupkg
      --publisher-name "Uno.Templates"
      --description "Uno.Templates"
      --description-url "https://github.com/${{ env.GITHUB_REPOSITORY }}"
      --azure-key-vault-managed-identity true
      --azure-key-vault-url "${{ secrets.SIGN_KEY_VAULT_URL }}"
      --azure-key-vault-certificate "${{ secrets.SIGN_KEY_VAULT_CERTIFICATE_ID }}"
      --verbosity information

  - name: Upload Signed Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: NuGet-Signed
      path: .\artifacts\NuGet
