name: "Sign Packages"
description: "Sign Packages"

inputs:
  sign-username:
    description: "The username to use for signing"
    required: true
  sign-password:
    description: "The password to use for signing"
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
      name: nuget-packages
      path: artifacts\NuGet

  - name: Setup .NET SDK
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '9.0.300'

  - name: Setup SignClient
    shell: pwsh
    run: |
      dotnet tool install --tool-path build SignClient

  - name: SignClient
    shell: pwsh
    run: |
      build\SignClient sign -i artifacts\NuGet\*.nupkg -c build\SignClient.json -r "${{ inputs.sign-username }}" -s "${{ inputs.sign-password }}" -n "Uno.Templates" -d "Uno.Templates" -u "https://github.com/unoplatform/uno.templates"

  - name: Upload Signed Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: NuGet-Signed
      path: .\artifacts\NuGet
